server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
      # 换成nginx的80端口，做集群
      server-addr: 192.168.1.64:80

management:
  endpoints:
    web:
      exposure:
        include: '*'